services:
  nexus:
    image: sonatype/nexus3:latest
    environment:
      - NEXUS_DATASTORE_NEXUS_USERNAME=${POSTGRES_USER}
      - NEXUS_DATASTORE_NEXUS_PASSWORD=${POSTGRES_PASSWORD}
      - NEXUS_DATASTORE_NEXUS_JDBCURL=jdbc\:postgresql\://db\:${POSTGRES_PORT}/${POSTGRES_DB}
    ports:
      - 6010:8081
    volumes:
      - nexus-data:/nexus-data
    networks:
      nexus:

  db:
    image: postgres:17
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGPORT=${POSTGRES_PORT}
    ports:
      - 127.0.0.1:${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-nexus-db.sql:/docker-entrypoint-initdb.d/init-nexus-db.sql
    networks:
      nexus:

networks:
  nexus:

volumes:
  nexus-data:
  postgres-data: